### PR TITLE
stages

### PR DESCRIPTION
**Pull request by sadohat**

### CODE REVIEW

**Comment by sadohat** [comment]
NOOOO WHY WOULD YOU DO THIS

**Comment by HJfod** [comment]
Please stop opening issues

**Comment by sadohat** [comment]
BUT

**Comment by sadohat** [comment]
THIS IS ACTUALLY USEFUL

**Comment by HJfod** [comment]
We know it's useful and we're glad you think so aswell, but please don't spam our repos with unnecessary issues. If you're interested in the project, there are other avenues to show it

**Pull request closed without merging**
